<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-19T06:28:47Z" name="NopCommerce - User" finished-at="2023-04-19T06:29:00Z" duration-ms="12925">
    <groups>
    </groups>
    <test started-at="2023-04-19T06:28:47Z" name="Run on Chrome" finished-at="2023-04-19T06:29:00Z" duration-ms="12925">
      <class name="com.nopcommerce.user.Level_15_P4_Allure">
        <test-method is-config="true" signature="initBeforeSuite()[pri:0, instance:com.nopcommerce.user.Level_15_P4_Allure@5432c277]" started-at="2023-04-19T06:28:47Z" name="initBeforeSuite" finished-at="2023-04-19T06:28:47Z" duration-ms="100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initBeforeSuite -->
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:com.nopcommerce.user.Level_15_P4_Allure@5432c277]" started-at="2023-04-19T06:28:47Z" name="beforeClass" finished-at="2023-04-19T06:28:53Z" duration-ms="6063" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="User_01_Register()[pri:0, instance:com.nopcommerce.user.Level_15_P4_Allure@5432c277]" started-at="2023-04-19T06:28:53Z" name="User_01_Register" finished-at="2023-04-19T06:28:57Z" duration-ms="3581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- User_01_Register -->
        <test-method signature="User_02_Login()[pri:0, instance:com.nopcommerce.user.Level_15_P4_Allure@5432c277]" started-at="2023-04-19T06:28:57Z" name="User_02_Login" finished-at="2023-04-19T06:28:59Z" duration-ms="1958" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.nopcommerce.user.Level_15_P4_Allure.User_02_Login(Level_15_P4_Allure.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- User_02_Login -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.nopcommerce.user.Level_15_P4_Allure@5432c277]" started-at="2023-04-19T06:28:59Z" name="afterClass" finished-at="2023-04-19T06:29:00Z" duration-ms="643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.nopcommerce.user.Level_15_P4_Allure -->
    </test> <!-- Run on Chrome -->
  </suite> <!-- NopCommerce - User -->
</testng-results>
